### PR TITLE
Better UIImage Support

### PR DESCRIPTION
**Pull request by bcapps**
This pull request is a proposal to improve the public API of `NYTScalingImageView` and the internal code of both that class and `NYTPhotoViewer` to elevate using normal `UIImage`s to a first-class behavior after the addition of animated GIF support.

Currently, on develop, `NYTScalingImageView` only has APIs that support `NSData`, which means that `NYTPhoto` objects that only contain a non-animated `UIImage` are shoehorned into an API that then causes `UIImages` to be converted to data (a potentially metadata-lossy conversion) in order to call these APIs, and then _back_ to `UIImage` objects internally in those methods. This is both less performant and more complex than an API that treats `UIImage` and `NSData` equally, as they are in the `NYTPhoto` protocol. This pull request adds that API and removes the need for converting images to data and then converting that data back to images again.

Additionally, the docs for these new APIs that take `NSData` were never updated to reflect that fact, so I have also updated those in this pull request.

### CODE REVIEW

**Comment by livings124** [comment]
+1, this would fix some speed issues we're having

**Comment by Twigz** [comment]
Proposal accepted, please fix conflicts and add tests.

**Comment by bcapps** [comment]
Okay. I've resolved the merge conflicts and added the tests. A couple notes:
* Since there are now two initializers that require mutually exclusive data, I've changed the nullability attribute from `nullable` on develop to the implicit `nonnull`. This change was intentional, since you shouldn't call one of the two initializers without this data.
* The nullability change seeped into the tests, where instead of passing `nil` I now just pass an initialized object.
* I also removed `NYTViewController` from the test target because it is not necessary for running the tests and was skewing the code coverage metric (which is now at 100% after that change).
* I have not updated the Swift test target because it looks like that target has not been updated in some time and contains many errors unrelated to these changes.

**Comment by cdzombak** [comment]
:+1:

**Comment by dzlobin** [comment]
:+1:

**Pull request merged**
