### PR TITLE
Carthage support

### LINKED ISSUE #61: Carthage support
Would be awesome to have Carthage support.

### LINKED ISSUE #62: Add umbrella header
It's unexpected that the following doesn't work:

```objc
#import <NYTPhotoViewer/NYTPhotoViewer.h>
```

It would be great if there was an umbrella header. This will be required for #61 anyway :)

### PR DESCRIPTION
**Pull request by MichaelSelsky**
Adds Carthage support by:

- Adding a framework scheme and sharing it
- Adding a bridging header which includes

``` objc
#import <NYTPhotoViewer/NYTPhotosViewController.h>
#import <NYTPhotoViewer/NYTPhoto.h>
#import <NYTPhotoViewer/NYTPhotosOverlayView.h>
```

- Creating a symlink to the pods project file in the root directory.

### Related Issues

- Closes #61 
- Closes #62

### CODE REVIEW

**Comment by MichaelSelsky** [comment]
Anyone who has used this project: what headers do you need public? Right now I have the following in the umbrella header:
```objc
#import <NYTPhotoViewer/NYTPhotosViewController.h>
#import <NYTPhotoViewer/NYTPhoto.h>
#import <NYTPhotoViewer/NYTPhotosOverlayView.h>
```

**Comment by hhanesand** [comment]
In my project, I have the the `NYTPhotosViewController` and the `NYTPhoto` classes imported for very basic usage. I don't think it would hurt to include the `NYTPhotosOverlayView` however.

**Comment by dasmer** [comment]
@MichaelSelsky what's the status on this. We're interested in Carthage support as well.

**Comment by dasmer** [comment]
@cdzombak @bcapps it looks like you guys are maintaining this repo. We'd really like to use `NYTPhotoViewer` with Carthage. Is `NYTPhotoViewer` still being maintained or is this repo dead?

**Comment by cdzombak** [comment]
> Is `NYTPhotoViewer` still being maintained or is this repo dead?

This photo viewer is currently shipping in the NY Times iOS app, so no, it is not dead.

**Comment by dasmer** [comment]
@cdzombak Great! We'd love to use `NYTPhotoViewer` with Carthage. Is there anything holding this PR?

**Comment by bdorfman** [comment]
+1 to Carthage support. We would like to use this in our app via Carthage as well. Happy to help with any testing or changes needed to get this to happen.

**Comment by livings124** [comment]
We'd like to use NYTPhotoViewer via Carthage. Is there anything holding this back still?

**Comment by gfontenot** [comment]
Is there any progress on this? Or is this just not going to happen?

**Comment by MichaelSelsky** [comment]
If the NYTimes wants me to attempt to reimplement this I can. Until then I am going to close this PR.

**Pull request closed without merging**
