### PR TITLE
Added Travis support

### PR DESCRIPTION
**Pull request by MichaelSelsky**
Added a functional .travis.yml resolving issue #33.

### CODE REVIEW

**Comment by MichaelSelsky** [comment]
Screenshot of completed Travis build. 

screenshot 2015-04-01 21 14 06

**Comment by mattbischoff** [comment]
You’re my hero.

**Comment by MichaelSelsky** [comment]
:D

**Comment by mattbischoff** [comment]
@Twigz :eyes:

**Comment by cdzombak** [comment]
Thanks, @MichaelSelsky! I am now figuring out who within our organization to talk to about getting this repo set up on Travis.

**Pull request merged**
