### PR TITLE
update to PINRemoteImage 3.0.1

### PR DESCRIPTION
**Pull request by mr-fixit**

### CODE REVIEW

**Comment by mr-fixit** [comment]
@ZevEisenberg, Cam wonders if there's a way to avoid pulling in libwebp...

**Comment by ZevEisenberg** [comment]
Yes: stop using Carthage, and use CocoaPods instead. It looks like the webp thing is a subspec of PINRemoteImage, but I don't know if subspecs are a thing in Carthage-land.

**Comment by mr-fixit** [comment]
Switching this whole repo to CocoaPods will cause more delay and diffs.

How about I revert this branch's commits into the Carthage/Checkouts directory?

Would you guys approve of this way to get 5.0.4 published soonest AND have the smallest diff?

Later, in another PR, I'll switch the repo from Carthage.

**Comment by mr-fixit** [comment]
> I don't know if subspecs are a thing in Carthage-land.

I checked [Carthage doc](https://github.com/Carthage/Carthage/blob/master/Documentation/)), they are not.

**Pull request closed without merging**
