### PR TITLE
Fix to close button not showing

### PR DESCRIPTION
**Pull request by eranmarom**
You can also remove the X images assets with this fix in place...

### CODE REVIEW

**Comment by cdzombak** [comment]
> Fix to close button not showing

Can you please expand on the problem you're seeing, and trying to fix in this PR? In particular, are you not seeing the Close/X button? On which iOS version[s]? Are you up to date on the latest `develop`? A recent PR (#80) should have resolved problems related to this.

**Comment by cdzombak** [comment]
A screenshot illustrating the issue you're seeing would also be helpful.

**Comment by eranmarom** [comment]
I did not see the close (X) button in my app on iOS 9 and iOS8. This behaviour was consistent when adding the NYTPhotoViewer pod both from release, and from the latest version of develop.

I did manage to see the close button when downloading the "NYTPhotoViewer-develop" branch from git and running the code example, but again, this did not work when I updated my pod file to use this version.

Regardless, the solution suggested works better in my mind, as it shows a smaller X icon in landscape mode (which was not the case when running the code example in develop branch), and it needs less lines of code. The only caveat I can think of is that if apple changes the look of the "stop" system item, it will impact the user of this library.

**Comment by Twigz** [comment]
Closing as resolved by #80. Currently we won't be changing the asset for the close button. Everything should be now be working as intended regarding this issue. If it is not, feel free to open an issue explaining the problem.

**Comment by eranmarom** [comment]
How about this bug: https://github.com/NYTimes/NYTPhotoViewer/issues/102 ?
It seems the issue was not yet resolved.

**Pull request closed without merging**
