### PR TITLE
Load bar button item images from the correct bundle

### LINKED ISSUE #64: Image Loading
There seems to be a problem with the way this library loads images from its resources bundle.

From the looks of it you guys are using `[UIImage imageNamed:]` in `NYTPhotosViewController`, which searches the main bundle. On my device, that doesn't work, and the image is not loaded. I'm not very familiar with the way Cocoapods works, but it may have something to do with the fact that I'm using `use_frameworks!` in my podfile.

I think the easiest way to fix this is to use `[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]` with the bundle received from `[NSBundle bundleForClass:]`, as that will load the image from the appropriate bundle.

Just as a side note, I see you guys are using `resources` and not `resource_bundles` in your podspec, and I think the cocoapods team has deprecated `resources` in favor of `resource_bundles`.

Thanks in advance for replies :+1:

### LINKED ISSUE #75: Close button not showing
I am using the latest version of NYT and everything is working absolutely fine except the close button is hidden since I switched to cocoapods use_frameworks. Does anyone have any idea how to solve this issue?

Thanks :)

EDIT: Seems to be related to this issue: https://github.com/NYTimes/NYTPhotoViewer/issues/64
I'm using cocoapods and use_frameworks as well.

### PR DESCRIPTION
**Pull request by cdzombak**
As part of this change, I'm using `resource_bundle` as [recommended by CocoaPods](https://guides.cocoapods.org/syntax/podspec.html).

After cutting a new version, this:
- closes #64 
- closes #75

### CODE REVIEW

**Comment by bcapps** [comment]
Does this change make NYTPhotoViewer's minimum version iOS 8 with the usage of imageNamed:inBundle: (which I think is an iOS 8 method)? If so, you may want to change the minimum version in the pod spec also.

**Comment by cdzombak** [comment]
Good catch, @bcapps. I'll add a pod spec change to this branch Monday. 

Collaborators: **do not merge** yet.

**Comment by cdzombak** [comment]
> Does this change make NYTPhotoViewer's minimum version iOS 8 with the usage of imageNamed:inBundle: (which I think is an iOS 8 method)? If so, you may want to change the minimum version in the pod spec also.

Done in https://github.com/NYTimes/NYTPhotoViewer/commit/f2572747e357bf8fe4774c5eeb60241fd538f39f

**Comment by dzlobin** [comment]
@cdzombak needs to be updated now

**Comment by cdzombak** [comment]
@dzlobin done in 072afb1

**Pull request merged**
