### PR TITLE
Added Carthage Support

### PR DESCRIPTION
**Pull request by davbeck**
This is done around the requirements and desires outlined in #61, meaning that it is a complete project restructuring.

I've included the framework in my own app using the following and so far everything is working as expected:

    github "davbeck/NYTPhotoViewer" "develop"

See my note on the issue in regards to GIF support. This is, in my opinion, the closest analogue to Cocoapods subspecs.

As for the resource bundle, I just made the folder a bundle itself. CocoaPods should create it's own bundle based off of the files in that folder/bundle and Carthage should recognize the folder as a bundle and embed it as such. No need to special case any code.

I did run `pod lib lint`, but I haven't tried to pull in the framework using CocoaPods just yet.

### CODE REVIEW

**Comment by cdzombak** [comment]
@davbeck this looks great, and I'm reviewing it today/tomorrow as I find time.

As a first small thing to fix, it looks like FLAnimatedImage is included in the NYTPhotoViewer project with an absolute path instead of "Relative to Group":

```
11FBDA7B1C87746600018169 /* FLAnimatedImage.framework */ = {isa = PBXFileReference; explicitFileType = wrapper.framework; name = FLAnimatedImage.framework; path = "/Users/davbeck/Library/Developer/Xcode/DerivedData/NYTPhotoViewer-cyvibeoaqesupbclsxbljcxwjqzw/Build/Products/Debug-iphoneos/FLAnimatedImage.framework"; sourceTree = "<absolute>"; };
```

screen shot 2016-03-03 at 14 45 23

Can you please push that small change to your branch, and I'll keep looking?

**Comment by davbeck** [comment]
Good catch. It opens up another issue though I wasn't aware of. At least on my Mac with Xcode 7.2.1 (7C1002), linking against the relative framework doesn't properly add the project as a dependency to the Example app and the projects from the workspace don't appear when adding dependencies manually.

I don't normally use workspaces with Carthage (it's not how the official Carthage docs recommend setting up projects) but I wanted to follow the ThoughtBot guide linked to in the issue.

**Comment by davbeck** [comment]
I think I've resolved that issue in the last commit by removing the workspace and just using a single project. I also did a `carthage update` in my own project to verify everything still works there.

**Comment by cdzombak** [comment]
This looks great, @davbeck. I've completed an initial review and some experimenting and I am ready to merge!

Will have a writeup on #63 shortly detailing what I've looked at and what next steps are for getting this into a release.

**Pull request merged**
