### PR TITLE
Set barButtonItem on UIActivityViewController

### PR DESCRIPTION
**Pull request by plu**

### CODE REVIEW

**Comment by bcapps** [comment]
This library currently supports iOS 7, but this change will only work in iOS 8 (when `popoverPresentationController` was introduced) and above.

**Comment by plu** [comment]
Oh sorry, that I've missed that, I'll rework the patch|! Thanks for the hint!

**Comment by plu** [comment]
Ping :)

**Comment by cdzombak** [comment]
@plu, thanks for your contribution!

**Comment by plu** [comment]
Thanks :+1:

**Pull request merged**
